# improve colors
set -g default-terminal 'screen-256color'

# act like vim
setw -g mode-keys vi

# enable mouse support (click and drag to select, pane-specific)
set -g mouse on

# vim-like visual selection in copy mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"

# copy to system clipboard when selecting with mouse
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"
