# improve colors
set -g default-terminal 'screen-256color'

# act like vim
setw -g mode-keys vi

# vim-like visual selection in copy mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
